name: Primer workflow
on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
    
      - name: Ejecutar codigo
        run: python3 test.py
