name: Primer workflow
on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
    
      - name: Descargar pytest
        run: pip install pytest

      - name: Ejecutar test
        run: pytest test.py
  evaluacion:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Ejecutar evaluacion
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
