name: Primer workflow
on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
    
      - name: Descargar pytest
        run: pip install pytest

      - name: Ejecutar test
        run: pytest test.py
